spring:
  application:
    name: first-admin-service
  zipkin:
    base-url: http://111.229.201.69:9411
  boot:
    admin:
      client:
        url: http://111.229.201.69:8084

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
