spring:
  application:
    name: first-zipkin
  boot:
    admin:
      client:
        url: http://111.229.201.69:8084

server:
  port: 9411


eureka:
  client:
    serviceUrl:
      defaultZone: http://111.229.201.69:8761/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info