spring:
  application:
    name: first-Zuul
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084
server:
  port: 8769

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    #api-a api-b是自定义的名字
    api-a:
      path: /api/a/**
      serviceId: first-ribbon
    api-b:
      path: /api/b/**
      serviceId: first-feign

